env: "dev" #local, dev, prod
cgo_enabled: "1"
connString: ""
redis_client:
  addr: ""
  user: ""
  pass: ""
  db: 0
  max_retries: 3
  dial_timeout: 5s
  timeout: 10s
http_server:
  address: "0.0.0.0:0000"
  timeout: 4s
  idle_timeout: 60s
  user: ""
  password: ""
