env: "dev" #local, dev, prod
cgo_enabled: "1"
connString: "postgres://admin:Aitusa2025!@34.89.141.175:1005/complaints?sslmode=disable"
redis_client:
  addr: "34.89.141.175:6379"
  user: ""
  pass: ""
  db: 0
  max_retries: 3
  dial_timeout: 5s
  timeout: 10s
http_server:
  address: "127.0.0.1:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "aitusa"
  password: "aitusa"
