env: "local" #local, dev, prod
cgo_enabled: "1"
connString: "postgresql://postgres:postgres@localhost:5432/complaintDB"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "aitusa"
  password: "aitusa"
